### ISSUE TITLE
Full Screen With no Screen OS Buttons (Sidebar)??

### ISSUE THREAD

**Issue by MarshMeadow** [Dovakiin0/animeworldz-mobile#6] opened 2022-12-22 02:22 UTC
It won't go Fullscreen, I still see my buttons to my phone and they won't go away.

**Comment by Dovakiin0** [comment] 2022-12-22 14:05
Hi @meadow5290, could you provide the brand and type of your mobile phone and a screen shot when in full screen

**Comment by Dovakiin0** [comment] 2022-12-26 15:51
Hi @meadow5290, the screen shots were unfortunately not uploaded. However I have applied some fixes. Try updating your app and see if the issue is solved.

**Comment by Dovakiin0** [comment] 2022-12-27 02:53
Glad to hear that. You can close this issue if this solves your problem.

**Closed** 2022-12-29 13:50 UTC
